import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import type { Plugin } from 'vite'

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const projectRoot = path.resolve(scriptDir, '..')

const SW_TEMPLATE = `/* generated by Vite — do not edit */
self.addEventListener('install', (event) => {
  event.waitUntil(self.skipWaiting())
})

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim())
})

importScripts('https://www.gstatic.com/firebasejs/12.15.0/firebase-app-compat.js')
importScripts('https://www.gstatic.com/firebasejs/12.15.0/firebase-messaging-compat.js')

firebase.initializeApp({
  apiKey: '__API_KEY__',
  authDomain: '__AUTH_DOMAIN__',
  projectId: '__PROJECT_ID__',
  storageBucket: '__STORAGE_BUCKET__',
  messagingSenderId: '__MESSAGING_SENDER_ID__',
  appId: '__APP_ID__',
})

const messaging = firebase.messaging()

messaging.onBackgroundMessage((payload) => {
  const title = payload.notification?.title || payload.data?.title || 'OrderQR'
  const options = {
    body: payload.notification?.body || payload.data?.body || '',
    icon: '/logochaomao.png',
    badge: '/logochaomao.png',
    tag: payload.data?.tag || 'ccm-push',
    vibrate: [200, 100, 200],
    data: payload.data || {},
  }
  return self.registration.showNotification(title, options)
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      if (clientList.length > 0) {
        return clientList[0].focus()
      }
      return clients.openWindow('/orders')
    }),
  )
})
`

function writeServiceWorker(env: Record<string, string | undefined>) {
  const content = SW_TEMPLATE.replace('__API_KEY__', env.VITE_FIREBASE_API_KEY ?? '')
    .replace('__AUTH_DOMAIN__', env.VITE_FIREBASE_AUTH_DOMAIN ?? '')
    .replace('__PROJECT_ID__', env.VITE_FIREBASE_PROJECT_ID ?? '')
    .replace('__STORAGE_BUCKET__', env.VITE_FIREBASE_STORAGE_BUCKET ?? '')
    .replace('__MESSAGING_SENDER_ID__', env.VITE_FIREBASE_MESSAGING_SENDER_ID ?? '')
    .replace('__APP_ID__', env.VITE_FIREBASE_APP_ID ?? '')

  writeFileSync(path.join(projectRoot, 'public/sw.js'), content, 'utf8')
}

export function generateMessagingSw(): Plugin {
  return {
    name: 'generate-messaging-sw',
    configResolved(config) {
      writeServiceWorker(config.env as Record<string, string | undefined>)
    },
    configureServer(server) {
      const envPath = path.join(projectRoot, '.env')
      let fileEnv: Record<string, string> = {}
      try {
        const raw = readFileSync(envPath, 'utf8')
        for (const line of raw.split('\n')) {
          const match = line.match(/^([^#=]+)=(.*)$/)
          if (match) fileEnv[match[1].trim()] = match[2].trim()
        }
      } catch {
        // no .env file
      }

      writeServiceWorker({ ...fileEnv, ...server.config.env })

      server.watcher.add(path.join(projectRoot, '.env'))
      server.watcher.on('change', (changed) => {
        if (changed === path.join(projectRoot, '.env')) {
          try {
            const raw = readFileSync(envPath, 'utf8')
            fileEnv = {}
            for (const line of raw.split('\n')) {
              const match = line.match(/^([^#=]+)=(.*)$/)
              if (match) fileEnv[match[1].trim()] = match[2].trim()
            }
          } catch {
            fileEnv = {}
          }
          writeServiceWorker({ ...fileEnv, ...server.config.env })
        }
      })
    },
  }
}
